'use strict';

const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const os = require('node:os');
const webpush = require('web-push');

const ENV_FILE = path.join(process.cwd(), '.env');
const USERS_FILE = process.env.CHAT_USERS_FILE || path.join(process.cwd(), 'config', 'chat-users.json');
const SETUP_STATE_FILE = process.env.SETUP_STATE_FILE || path.join(process.cwd(), 'data', 'setup-complete.json');
const GENERATED_DIR = path.join(process.cwd(), 'data', 'setup-generated');
const SERVICE_FILE = path.join(GENERATED_DIR, 'fastify-api.service');
const NGINX_FILE = path.join(GENERATED_DIR, 'nginx.chat.conf');
const CLOUDFLARE_FILE = path.join(GENERATED_DIR, 'cloudflared.config.yml');
const APP_NAME = 'cabras-chat';

function normalizeUsername(value) {
  return String(value || '').trim().slice(0, 30);
}

function normalizeRole(value) {
  return String(value || '').trim().toLowerCase() === 'admin' ? 'admin' : 'user';
}

function normalizeHost(value) {
  return String(value || '').trim() || '127.0.0.1';
}

function normalizeRoomName(value) {
  return String(value || '').replace(/\s+/g, ' ').trim().slice(0, 60);
}

function normalizeHostname(value) {
  return String(value || '').trim().toLowerCase().replace(/^https?:\/\//, '').replace(/\/.*$/, '');
}

function normalizeVapidEmail(value) {
  const raw = String(value || '').trim();
  if (!raw) return 'mailto:admin@example.com';
  return raw.startsWith('mailto:') ? raw : `mailto:${raw}`;
}

function toPort(value) {
  const parsed = parseInt(value, 10);
  if (!Number.isFinite(parsed) || parsed < 1 || parsed > 65535) return 3000;
  return parsed;
}

function isTruthy(value) {
  return value === true || value === 'true' || value === 1 || value === '1';
}

function getRequestAddress(request) {
  const forwarded = String(request.headers['x-forwarded-for'] || '').split(',')[0].trim();
  return forwarded || String(request.ip || request.socket?.remoteAddress || '').trim();
}

function isLocalAccess(request) {
  const address = getRequestAddress(request)
    .replace(/^::ffff:/, '')
    .replace(/^\[|\]$/g, '');
  const host = String(request.headers['x-forwarded-host'] || request.headers.host || '').toLowerCase();

  return (
    address === '127.0.0.1' ||
    address === '::1' ||
    address === '' ||
    address.startsWith('10.') ||
    address.startsWith('192.168.') ||
    /^172\.(1[6-9]|2\d|3[0-1])\./.test(address) ||
    host.includes('raspberrypi.local') ||
    host.includes('localhost')
  );
}

function canWrite(filePath) {
  try {
    fs.accessSync(path.dirname(filePath), fs.constants.W_OK);
    return true;
  } catch {
    return false;
  }
}

function ensureDir(dirPath) {
  fs.mkdirSync(dirPath, { recursive: true });
}

function readJsonFile(filePath, fallback) {
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf8'));
  } catch {
    return fallback;
  }
}

function readUsers(filePath) {
  const parsed = readJsonFile(filePath, []);
  if (!Array.isArray(parsed)) return [];
  return parsed
    .map((entry) => ({
      username: normalizeUsername(entry?.username),
      role: normalizeRole(entry?.role),
    }))
    .filter((entry) => entry.username);
}

function hasUsableUsers(filePath) {
  const users = readUsers(filePath);
  return users.length > 0 && users.some((user) => user.role === 'admin');
}

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const values = {};
  const lines = fs.readFileSync(filePath, 'utf8').split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx === -1) continue;
    const key = trimmed.slice(0, idx).trim();
    const value = trimmed.slice(idx + 1);
    values[key] = value;
  }
  return values;
}

function escapeEnvValue(value) {
  return String(value ?? '').replace(/\n/g, '\\n');
}

function renderEnvFile(values) {
  return [
    '# Generated by cabras-chat setup wizard',
    '',
    '# Core app',
    `APP_NAME=${escapeEnvValue(values.APP_NAME)}`,
    `NODE_ENV=${escapeEnvValue(values.NODE_ENV)}`,
    `HOST=${escapeEnvValue(values.HOST)}`,
    `PORT=${escapeEnvValue(values.PORT)}`,
    '',
    '# Legacy REST API',
    `API_PREFIX=${escapeEnvValue(values.API_PREFIX)}`,
    `DB_PATH=${escapeEnvValue(values.DB_PATH)}`,
    '',
    '# Chat auth',
    `CHAT_USERS_FILE=${escapeEnvValue(values.CHAT_USERS_FILE)}`,
    `TOKEN_SECRET=${escapeEnvValue(values.TOKEN_SECRET)}`,
    `DEFAULT_ADMIN_USERNAME=${escapeEnvValue(values.DEFAULT_ADMIN_USERNAME)}`,
    `DEFAULT_ROOM_NAME=${escapeEnvValue(values.DEFAULT_ROOM_NAME)}`,
    '',
    '# Web Push',
    `VAPID_PUBLIC_KEY=${escapeEnvValue(values.VAPID_PUBLIC_KEY)}`,
    `VAPID_PRIVATE_KEY=${escapeEnvValue(values.VAPID_PRIVATE_KEY)}`,
    `VAPID_EMAIL=${escapeEnvValue(values.VAPID_EMAIL)}`,
    '',
  ].join('\n');
}

function detectSetupState() {
  const markerExists = fs.existsSync(SETUP_STATE_FILE);
  const envExists = fs.existsSync(ENV_FILE);
  const usersExists = fs.existsSync(USERS_FILE);
  const legacyComplete = envExists && usersExists && hasUsableUsers(USERS_FILE);
  const forced = isTruthy(process.env.FORCE_SETUP_MODE);
  return {
    forced,
    markerExists,
    envExists,
    usersExists,
    legacyComplete,
    active: forced || !(markerExists || legacyComplete),
  };
}

function setupDefaults(request) {
  const envValues = parseEnvFile(ENV_FILE);
  const users = readUsers(USERS_FILE);
  const adminUser = users.find((entry) => entry.role === 'admin') || users[0] || null;
  const requestHost = String(request.headers['x-forwarded-host'] || request.headers.host || '').split(',')[0].trim();

  return {
    chatName: normalizeRoomName(envValues.DEFAULT_ROOM_NAME || 'Raspi Chat') || 'Raspi Chat',
    hostname: normalizeHostname(envValues.PUBLIC_HOSTNAME || requestHost),
    host: normalizeHost(envValues.HOST || '127.0.0.1'),
    port: toPort(envValues.PORT || 3000),
    networkMode: envValues.SETUP_NETWORK_MODE || 'lan',
    adminUsername: normalizeUsername(envValues.DEFAULT_ADMIN_USERNAME || adminUser?.username || 'Giovanni') || 'Giovanni',
    vapidEmail: normalizeVapidEmail(envValues.VAPID_EMAIL || 'admin@example.com'),
    enableWebPush: !!(envValues.VAPID_PUBLIC_KEY && envValues.VAPID_PRIVATE_KEY),
    users,
  };
}

function systemChecks() {
  const state = detectSetupState();
  let cloudflaredDetected = false;
  try {
    fs.accessSync('/usr/bin/cloudflared', fs.constants.X_OK);
    cloudflaredDetected = true;
  } catch {}
  return {
    nodeVersion: process.version,
    platform: `${os.platform()} ${os.arch()}`,
    cwd: process.cwd(),
    envFileExists: state.envExists,
    usersFileExists: state.usersExists,
    setupMarkerExists: state.markerExists,
    generatedDirWritable: canWrite(path.join(GENERATED_DIR, 'check')),
    rootWritable: canWrite(path.join(process.cwd(), '.env')),
    cloudflaredDetected,
    serviceTemplateTarget: SERVICE_FILE,
    nginxTemplateTarget: NGINX_FILE,
    cloudflareTemplateTarget: CLOUDFLARE_FILE,
  };
}

function renderServiceFile({ appDir, nodePath, userName }) {
  return [
    '[Unit]',
    'Description=Fastify API',
    'After=network.target',
    '',
    '[Service]',
    `User=${userName}`,
    `WorkingDirectory=${appDir}`,
    `ExecStart=${nodePath} server.js`,
    'Restart=always',
    'RestartSec=5',
    'Environment=NODE_ENV=production',
    '',
    '[Install]',
    'WantedBy=multi-user.target',
    '',
  ].join('\n');
}

function renderNginxFile({ hostname, port }) {
  const targetHost = hostname || 'chat.example.com';
  return [
    'server {',
    '  listen 80;',
    `  server_name ${targetHost};`,
    '',
    '  location / {',
    `    proxy_pass http://127.0.0.1:${port};`,
    '    proxy_http_version 1.1;',
    '    proxy_set_header Host $host;',
    '    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;',
    '    proxy_set_header X-Forwarded-Proto $scheme;',
    '    proxy_set_header Upgrade $http_upgrade;',
    '    proxy_set_header Connection "upgrade";',
    '  }',
    '}',
    '',
  ].join('\n');
}

function renderCloudflareFile({ hostname, port }) {
  return [
    'tunnel: <TUNNEL_ID>',
    'credentials-file: /home/<user>/.cloudflared/<TUNNEL_ID>.json',
    '',
    'ingress:',
    `  - hostname: ${hostname || 'chat.example.com'}`,
    `    service: http://127.0.0.1:${port}`,
    '  - service: http_status:404',
    '',
  ].join('\n');
}

function setupResponsePayload(request) {
  const state = detectSetupState();
  return {
    setupMode: state.active,
    setupComplete: !state.active,
    localOnly: !isTruthy(process.env.SETUP_ALLOW_REMOTE),
    isLocalRequest: isLocalAccess(request),
    defaults: setupDefaults(request),
    checks: systemChecks(),
    paths: {
      envFile: ENV_FILE,
      usersFile: USERS_FILE,
      setupStateFile: SETUP_STATE_FILE,
      generatedDir: GENERATED_DIR,
      serviceFile: SERVICE_FILE,
      nginxFile: NGINX_FILE,
      cloudflareFile: CLOUDFLARE_FILE,
    },
  };
}

function ensureSetupAllowed(request, reply) {
  const state = detectSetupState();
  if (!state.active) {
    reply.redirect('/chat');
    return false;
  }
  if (!isTruthy(process.env.SETUP_ALLOW_REMOTE) && !isLocalAccess(request)) {
    reply.code(403).send({ error: 'Setup is available only from the local network' });
    return false;
  }
  return true;
}

function buildUserList(adminUsername, adminPassword, rawUsers) {
  const seen = new Set();
  const result = [];

  const pushUser = (username, password, role) => {
    const normalizedUsername = normalizeUsername(username);
    const normalizedRole = normalizeRole(role);
    const normalizedPassword = String(password || '');
    if (!normalizedUsername || !normalizedPassword) return;
    const key = normalizedUsername.toLowerCase();
    if (seen.has(key)) return;
    seen.add(key);
    result.push({
      username: normalizedUsername,
      password: normalizedPassword,
      role: normalizedRole,
    });
  };

  pushUser(adminUsername, adminPassword, 'admin');
  for (const entry of rawUsers || []) {
    pushUser(entry?.username, entry?.password, entry?.role);
  }

  return result;
}

async function setupRoutes(app) {
  app.get('/setup', async (request, reply) => {
    if (!ensureSetupAllowed(request, reply)) return;
    reply
      .type('text/html; charset=utf-8')
      .header('Cache-Control', 'no-store')
      .send(fs.readFileSync(path.join(process.cwd(), 'public', 'setup.html'), 'utf8'));
  });

  app.get('/setup/state', async (request, reply) => {
    if (!ensureSetupAllowed(request, reply)) return;
    return setupResponsePayload(request);
  });

  app.post('/setup/apply', async (request, reply) => {
    if (!ensureSetupAllowed(request, reply)) return;

    const body = request.body || {};
    const chatName = normalizeRoomName(body.chatName || 'Raspi Chat') || 'Raspi Chat';
    const networkMode = ['lan', 'nginx', 'cloudflare'].includes(body.networkMode) ? body.networkMode : 'lan';
    const host = normalizeHost(body.host || '127.0.0.1');
    const port = toPort(body.port || 3000);
    const hostname = normalizeHostname(body.hostname);
    const adminUsername = normalizeUsername(body.adminUsername);
    const adminPassword = String(body.adminPassword || '');
    const vapidEmail = normalizeVapidEmail(body.vapidEmail || 'admin@example.com');
    const enableWebPush = body.enableWebPush !== false;

    if (!adminUsername) return reply.code(400).send({ error: 'Missing admin username' });
    if (adminPassword.length < 8) return reply.code(400).send({ error: 'Admin password is too short (minimum 8 characters)' });
    if ((networkMode === 'nginx' || networkMode === 'cloudflare') && !hostname) {
      return reply.code(400).send({ error: 'A public hostname is required for nginx or Cloudflare' });
    }

    const users = buildUserList(adminUsername, adminPassword, body.users);
    if (!users.length) return reply.code(400).send({ error: 'At least one admin user is required' });

    const existingEnv = parseEnvFile(ENV_FILE);
    const vapidKeys = enableWebPush
      ? (
        existingEnv.VAPID_PUBLIC_KEY && existingEnv.VAPID_PRIVATE_KEY
          ? { publicKey: existingEnv.VAPID_PUBLIC_KEY, privateKey: existingEnv.VAPID_PRIVATE_KEY }
          : webpush.generateVAPIDKeys()
      )
      : { publicKey: '', privateKey: '' };

    ensureDir(path.join(process.cwd(), 'config'));
    ensureDir(path.join(process.cwd(), 'data'));
    ensureDir(path.join(process.cwd(), 'data', 'uploads'));
    ensureDir(path.join(process.cwd(), 'public', 'backgrounds'));
    ensureDir(GENERATED_DIR);

    const envValues = {
      APP_NAME,
      NODE_ENV: 'production',
      HOST: host,
      PORT: String(port),
      API_PREFIX: existingEnv.API_PREFIX || '/api/v1',
      DB_PATH: existingEnv.DB_PATH || path.join(process.cwd(), 'data', 'app.db'),
      CHAT_USERS_FILE: USERS_FILE,
      TOKEN_SECRET: existingEnv.TOKEN_SECRET || crypto.randomBytes(32).toString('hex'),
      DEFAULT_ADMIN_USERNAME: adminUsername,
      DEFAULT_ROOM_NAME: chatName,
      VAPID_PUBLIC_KEY: vapidKeys.publicKey,
      VAPID_PRIVATE_KEY: vapidKeys.privateKey,
      VAPID_EMAIL: enableWebPush ? vapidEmail : '',
      PUBLIC_HOSTNAME: hostname,
      SETUP_NETWORK_MODE: networkMode,
    };

    fs.writeFileSync(ENV_FILE, renderEnvFile(envValues), 'utf8');
    fs.writeFileSync(USERS_FILE, JSON.stringify(users, null, 2) + '\n', 'utf8');
    fs.writeFileSync(
      SETUP_STATE_FILE,
      JSON.stringify({
        installedAt: new Date().toISOString(),
        chatName,
        adminUsername,
        hostname,
        networkMode,
        users: users.map((entry) => ({ username: entry.username, role: entry.role })),
      }, null, 2) + '\n',
      'utf8'
    );

    const userName = os.userInfo().username;
    fs.writeFileSync(SERVICE_FILE, renderServiceFile({ appDir: process.cwd(), nodePath: process.execPath, userName }), 'utf8');
    fs.writeFileSync(NGINX_FILE, renderNginxFile({ hostname, port }), 'utf8');
    fs.writeFileSync(CLOUDFLARE_FILE, renderCloudflareFile({ hostname, port }), 'utf8');

    const nextCommands = [
      `cp ${SERVICE_FILE} /etc/systemd/system/fastify-api.service`,
      'systemctl daemon-reload',
      'systemctl enable --now fastify-api',
    ];
    if (networkMode === 'nginx') {
      nextCommands.push(`cp ${NGINX_FILE} /etc/nginx/sites-available/cabras-chat.conf`);
      nextCommands.push('ln -sf /etc/nginx/sites-available/cabras-chat.conf /etc/nginx/sites-enabled/cabras-chat.conf');
      nextCommands.push('nginx -t && systemctl reload nginx');
    }

    return {
      ok: true,
      setupComplete: true,
      generated: {
        envFile: ENV_FILE,
        usersFile: USERS_FILE,
        serviceFile: SERVICE_FILE,
        nginxFile: NGINX_FILE,
        cloudflareFile: CLOUDFLARE_FILE,
      },
      publicUrl: hostname
        ? `${networkMode === 'lan' ? 'http' : 'https'}://${hostname}/chat`
        : `http://${host}:${port}/chat`,
      nextCommands,
      notes: [
        'Restart or enable the systemd service using the generated file.',
        'For Cloudflare Tunnel, use cloudflared.config.yml as the base and fill in the tunnel ID.',
        'After the first restart, the /setup page will be hidden and access will switch to the chat.',
      ],
    };
  });
}

module.exports = setupRoutes;
